Repository Csharp-Team-Stamo/UpSkill, pull requests merged in 2021-11, with the labels that each got.

#108 Implemented SendGrid integration
  UpSkill/Api/Controllers/WelcomePageController.cs
  UpSkill/Api/Startup.cs
  UpSkill/Api/UpSkill.Api.csproj
  UpSkill/Api/appsettings.json
  UpSkill/ClientSide/Pages/DemoNotSent.razor
  UpSkill/ClientSide/Pages/DemoSuccessfullySent.razor
  UpSkill/ClientSide/Pages/WelcomePage.razor
  UpSkill/ClientSide/Pages/WelcomePage.razor.cs
  UpSkill/ClientSide/wwwroot/images/DemoFail.jpg
  UpSkill/ClientSide/wwwroot/images/DemoSuccess.png
  UpSkill/Infrastructure/UpSkill.Infrastructure.Common/GlobalConstants.cs
  UpSkill/Services/UpSkill.Services.Data/Contracts/IEmailSender.cs
  UpSkill/Services/UpSkill.Services.Data/EmailSender.cs
  UpSkill/Services/UpSkill.Services.Data/SendGridEmailSenderOptions.cs
  UpSkill/Services/UpSkill.Services.Data/UpSkill.Services.Data.csproj
Labels: Functional Dependency

#140 Added basic query panel
  UpSkill/ClientSide/Controls/QueryPanel.razor
  UpSkill/ClientSide/Controls/QueryPanel.razor.css
  UpSkill/ClientSide/Pages/Courses.razor
  UpSkill/ClientSide/Pages/CoursesCatalogue.razor
  UpSkill/ClientSide/wwwroot/css/colors.css
  UpSkill/ClientSide/wwwroot/images/arrows.svg
  UpSkill/ClientSide/wwwroot/images/book.svg
Labels: enhancement

#144 Martin rework resourcecard component 100
  UpSkill/ClientSide/Controls/ResourceCard.razor
  UpSkill/ClientSide/Controls/ResourceCard.razor.css
  UpSkill/ClientSide/Pages/Courses.razor
Labels: refactoring

#143 Renamed all DTOs to models
  UpSkill/Api/Controllers/AccountsController.cs
  UpSkill/ClientSide/Authentication/Services/AuthenticationService.cs
  UpSkill/ClientSide/Authentication/Services/Contracts/IAuthenticationService.cs
  UpSkill/ClientSide/Infrastructure/Services/Contracts/IRegistrationService.cs
  UpSkill/ClientSide/Infrastructure/Services/RegistrationService.cs
  UpSkill/ClientSide/Pages/LogIn.razor.cs
  UpSkill/ClientSide/Pages/Registration.razor.cs
  UpSkill/Infrastructure/UpSkill.Infrastructure.Models/Account/AuthenticationResponse.cs
  UpSkill/Infrastructure/UpSkill.Infrastructure.Models/Account/RegistrationResponse.cs
  UpSkill/Infrastructure/UpSkill.Infrastructure.Models/Account/UserAuthentication.cs
  UpSkill/Infrastructure/UpSkill.Infrastructure.Models/Account/UserRegistrationModel.cs
Labels: refactoring

#145 Implemented owner/coahes page functionality 136
  UpSkill/Api/Controllers/CoachesController.cs
  UpSkill/Api/Startup.cs
  UpSkill/Api/appsettings.json
  UpSkill/ClientSide/Controls/AddEmployeeModal.razor
  UpSkill/ClientSide/Controls/CoachCard.razor
  UpSkill/ClientSide/Controls/Header.razor
  UpSkill/ClientSide/Infrastructure/Services/CoachesService.cs
  UpSkill/ClientSide/Infrastructure/Services/Contracts/ICoachesService.cs
  UpSkill/ClientSide/Pages/Coaches.razor
  UpSkill/ClientSide/Pages/Coaches.razor.css
  UpSkill/ClientSide/Pages/CoachesCatalog.razor
  UpSkill/ClientSide/Pages/CoachesCatalogue.razor
  UpSkill/ClientSide/Pages/CoursesCatalog.razor
  UpSkill/ClientSide/Pages/LogIn.razor
  UpSkill/ClientSide/Pages/LogIn.razor.cs
  UpSkill/ClientSide/Pages/Registration.razor.cs
  UpSkill/ClientSide/Pages/WelcomePage.razor
  UpSkill/ClientSide/Program.cs
  UpSkill/ClientSide/UpSkill.ClientSide.csproj
  UpSkill/ClientSide/_Imports.razor
  UpSkill/Data/Models/Owner.cs
  UpSkill/Infrastructure/UpSkill.Infrastructure.Models/Coaches/CoachInListCatalogModel.cs
  UpSkill/Infrastructure/UpSkill.Infrastructure.Models/Coaches/CoachesListingCatalogModel.cs
  UpSkill/Services/UpSkill.Services.Data/AccountsService.cs
  UpSkill/Services/UpSkill.Services.Data/CoachesService.cs
  UpSkill/Services/UpSkill.Services.Data/Contracts/ICoachesService.cs
  UpSkill/Services/UpSkill.Services.Data/Contracts/IOwnerService.cs
  UpSkill/Services/UpSkill.Services.Data/OwnerService.cs
Labels: enhancement

#147 added checkboxes in coaches catalog
  UpSkill/ClientSide/Controls/CheckboxesPanel.razor
  UpSkill/ClientSide/Controls/CheckboxesPanel.razor.css
  UpSkill/ClientSide/Controls/CoachCard.razor.css
  UpSkill/ClientSide/Controls/EmployeesTable.razor
  UpSkill/ClientSide/Pages/CoachesCatalog.razor
  UpSkill/ClientSide/Program.cs
  UpSkill/ClientSide/wwwroot/css/app.css
  UpSkill/ClientSide/wwwroot/css/colors.css
  UpSkill/ClientSide/wwwroot/images/coachesCatalog/CoachCatalogCheckboxImg.svg
  UpSkill/Services/UpSkill.Services.Data/Contracts/IEmailSender.cs
  UpSkill/Services/UpSkill.Services.Data/EmailSender.cs
  UpSkill/Services/UpSkill.Services.Data/SendGridEmailSenderOptions.cs
Labels: enhancement

#161 Added sorting caoches catalog 148
  UpSkill/Api/Controllers/AccountsController.cs
  UpSkill/Api/Controllers/CategoryController.cs
  UpSkill/Api/Controllers/CoachesController.cs
  UpSkill/Api/Controllers/LanguagesController.cs
  UpSkill/Api/Controllers/WeatherForecastController.cs
  UpSkill/Api/Startup.cs
  UpSkill/Api/WeatherForecast.cs
  UpSkill/Api/appsettings.json
  UpSkill/ClientSide/Controls/CheckboxesPanel.razor
  UpSkill/ClientSide/Controls/CoachCard.razor
  UpSkill/ClientSide/Controls/EmployeesTable.razor
  UpSkill/ClientSide/Infrastructure/Extensions/AuthenticationStateExtension.cs
  UpSkill/ClientSide/Infrastructure/Services/CoachesService.cs
  UpSkill/ClientSide/Pages/Coaches.razor
  UpSkill/ClientSide/Pages/CoachesCatalog.razor
  UpSkill/ClientSide/Pages/Counter.razor
  UpSkill/ClientSide/Pages/FetchData.razor
  UpSkill/ClientSide/_Imports.razor
  UpSkill/Infrastructure/UpSkill.Infrastructure.Models/Coaches/CoachInListCatalogModel.cs
  UpSkill/Infrastructure/UpSkill.Infrastructure.Models/Coaches/SortingTermsCoachesModel.cs
  UpSkill/Services/UpSkill.Services.Data/CategoriesService.cs
  UpSkill/Services/UpSkill.Services.Data/CoachesService.cs
  UpSkill/Services/UpSkill.Services.Data/Contracts/ICategoriesService.cs
  UpSkill/Services/UpSkill.Services.Data/Contracts/IEmployeesService.cs
  UpSkill/Services/UpSkill.Services.Data/Contracts/ILanguagesService.cs
  UpSkill/Services/UpSkill.Services.Data/EmployeesService.cs
  UpSkill/Services/UpSkill.Services.Data/LanguagesService.cs
Labels: enhancement

#127 Implemented Super admin Login
  UpSkill/ClientSide/App.razor
  UpSkill/ClientSide/Pages/SignUp.razor
  UpSkill/ClientSide/Pages/SuperAdminLogin.razor
  UpSkill/ClientSide/Pages/SuperAdminLogin.razor.cs
  UpSkill/ClientSide/Pages/SuperAdminLogin.razor.css
  UpSkill/ClientSide/wwwroot/images/SuperAdminPersonMockUp.svg
Labels: enhancement

#135 Implemented some new features and fixed some problems
  UpSkill/ClientSide/Controls/CoursesTopCard.razor
  UpSkill/ClientSide/Controls/CoursesTopCard.razor.css
  UpSkill/ClientSide/Controls/Header.razor.css
  UpSkill/ClientSide/Pages/AddCourse.razor
  UpSkill/ClientSide/Pages/Courses.razor
  UpSkill/ClientSide/Pages/WelcomePage.razor
  UpSkill/ClientSide/Pages/WelcomePage.razor.css
  UpSkill/ClientSide/Shared/NoMenuLayout.razor
  UpSkill/ClientSide/wwwroot/images/CoursesTopBackground.svg
  UpSkill/ClientSide/wwwroot/images/CoursesTopImage.svg
  UpSkill/ClientSide/wwwroot/images/PlusButton.svg
Labels: bug, enhancement

#173 Implemented logic Admin Course Delete
  UpSkill/Services/UpSkill.Services.Data/AdminCourseService.cs
Labels: bug

#170 Added logic in AdminCoachService.Delete()
  UpSkill/Services/UpSkill.Services.Data/AdminCoachService.cs
Labels: bug

#186 Moved All Admin route components from Pages
  UpSkill/Api/Startup.cs
  UpSkill/ClientSide/Pages/Admin/AdminCategories.razor
  UpSkill/ClientSide/Pages/Admin/AdminCategories.razor.css
  UpSkill/ClientSide/Pages/Admin/AdminClients.razor
  UpSkill/ClientSide/Pages/Admin/AdminClients.razor.css
  UpSkill/ClientSide/Pages/Admin/AdminCoach.razor
  UpSkill/ClientSide/Pages/Admin/AdminCoach.razor.cs
  UpSkill/ClientSide/Pages/Admin/AdminCoachEdit.razor
  UpSkill/ClientSide/Pages/Admin/AdminCoachEdit.razor.cs
  UpSkill/ClientSide/Pages/Admin/AdminCoaches.razor
  UpSkill/ClientSide/Pages/Admin/AdminCourse.razor
  UpSkill/ClientSide/Pages/Admin/AdminCourse.razor.cs
  UpSkill/ClientSide/Pages/Admin/AdminCourseDetails.razor
  UpSkill/ClientSide/Pages/Admin/AdminCourseEdit.razor
  UpSkill/ClientSide/Pages/Admin/AdminCourseEdit.razor.cs
  UpSkill/ClientSide/Pages/Admin/AdminCourses.razor
  UpSkill/ClientSide/Pages/Admin/AdminDashboard.razor
  UpSkill/ClientSide/Pages/Admin/AdminLanguages.razor
  UpSkill/ClientSide/Pages/Admin/AdminLanguages.razor.css
  UpSkill/ClientSide/Pages/Admin/AdminProfile.razor
  UpSkill/ClientSide/Pages/Admin/AdminRevenue.razor
  UpSkill/ClientSide/Pages/Admin/AdminRevenue.razor.css
  UpSkill/ClientSide/Pages/AdminCourseEdit.razor.cs
  UpSkill/Data/UpSkill.Data.csproj
Labels: enhancement
